# Generated by Django 2.0 on 2020-02-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psytests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentalevaluation',
            options={'ordering': ['eval_id'], 'verbose_name': '心理测评', 'verbose_name_plural': '心理测评'},
        ),
        migrations.AlterModelOptions(
            name='userevaluation',
            options={'verbose_name': '用户评论', 'verbose_name_plural': '用户评论'},
        ),
        migrations.AlterModelOptions(
            name='userreviewforevaluation',
            options={'verbose_name': '用户评价', 'verbose_name_plural': '用户评价'},
        ),
    ]
