# Generated by Django 2.0 on 2020-02-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psytests', '0002_auto_20200224_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userevaluation',
            options={'verbose_name': '用户测评信息', 'verbose_name_plural': '用户测评信息'},
        ),
    ]
