# Generated by Django 2.0 on 2020-02-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytests', '0004_auto_20200224_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalevaluation',
            name='is_online',
            field=models.CharField(choices=[('type1', 'intro1'), ('type2', 'intro2'), ('type3', 'intro3')], max_length=30),
        ),
    ]
