# Generated by Django 2.0 on 2020-02-24 13:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('psytests', '0005_auto_20200224_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalevaluation',
            name='eval_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('type1', '成长'), ('type2', '情感'), ('type3', '人际关系')], max_length=17),
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='is_online',
            field=models.CharField(choices=[(1, '在线'), (2, '离线'), (3, '完善中')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userevaluation',
            name='payment_status',
            field=models.CharField(choices=[('paid', '已付款'), ('not paid', '未付款')], max_length=20),
        ),
    ]
