# Generated by Django 2.0 on 2020-02-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytests', '0006_auto_20200224_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalevaluation',
            name='eval_type',
            field=models.CharField(choices=[('type1', '成长'), ('type2', '情感'), ('type3', '人际关系')], max_length=100),
        ),
    ]
