# Generated by Django 2.0 on 2020-02-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytests', '0007_auto_20200224_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalevaluation',
            name='is_online',
            field=models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('inprogress', '完善中')], max_length=30),
        ),
    ]
