# Generated by Django 2.0 on 2020-03-07 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psytests', '0008_auto_20200224_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvalQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.IntegerField(auto_created=True, verbose_name='问题id')),
                ('q_desc', models.CharField(max_length=3000, verbose_name='问题描述')),
                ('reverse_scoring', models.BooleanField(choices=[(False, '正向'), (True, '反向')], default=False, verbose_name='反向计分')),
                ('dimension', models.IntegerField(choices=[(1, '一'), (2, '二'), (3, '三')], default=1, verbose_name='维度')),
                ('eval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psytests.MentalEvaluation', verbose_name='对应测评')),
            ],
            options={
                'verbose_name': '测评问题',
                'verbose_name_plural': '测评问题',
                'ordering': ['q_id'],
            },
        ),
    ]
