# Generated by Django 2.0 on 2020-03-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytests', '0009_evalquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.IntegerField(auto_created=True, verbose_name='选项id')),
                ('o_desc', models.CharField(max_length=3000, verbose_name='选项描述')),
                ('question', models.ManyToManyField(to='psytests.EvalQuestion', verbose_name='对应问题')),
            ],
            options={
                'verbose_name': '选项',
                'verbose_name_plural': '选项',
                'ordering': ['o_id'],
            },
        ),
    ]
