# Generated by Django 2.0 on 2020-03-23 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psytests', '0010_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreviewforevaluation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
