# Generated by Django 2.0 on 2020-03-24 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psytests', '0011_auto_20200323_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvalQuestionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psytests.MentalEvaluation', verbose_name='测评id')),
                ('o_id', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='psytests.Options', verbose_name='选项id')),
                ('q_id', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='psytests.EvalQuestion', verbose_name='问题id')),
                ('user_id', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='psytests.UserEvaluation', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '用户id',
                'verbose_name_plural': '用户id',
                'ordering': ['user_id'],
            },
        ),
    ]
