# Generated by Django 2.0 on 2020-03-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytests', '0011_auto_20200323_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalevaluation',
            name='created_on',
            field=models.DateTimeField(max_length=200),
        ),
    ]
