# Generated by Django 2.0 on 2020-03-29 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytests', '0012_auto_20200326_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evalquestion',
            name='eval',
        ),
        migrations.RemoveField(
            model_name='userevaluation',
            name='mentalEvaluation',
        ),
        migrations.RemoveField(
            model_name='userreviewforevaluation',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='mentalevaluation',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='mentalevaluation',
            name='ques_num',
        ),
        migrations.RemoveField(
            model_name='mentalevaluation',
            name='state',
        ),
        migrations.AddField(
            model_name='mentalevaluation',
            name='dimension',
            field=models.IntegerField(choices=[(1, '一'), (2, '二'), (3, '三')], default=1, verbose_name='问题维度'),
        ),
        migrations.AddField(
            model_name='mentalevaluation',
            name='reverse_scoring',
            field=models.BooleanField(choices=[(False, '正向'), (True, '反向')], default=False, verbose_name='反向计分'),
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now, max_length=200, verbose_name='测评创建日期'),
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='eval_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='测评id'),
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='eval_type',
            field=models.CharField(choices=[('type1', '成长'), ('type2', '情感'), ('type3', '人际关系'), ('type4', '其他')], max_length=100, verbose_name='测评类型'),
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='intro',
            field=models.TextField(max_length=2000, verbose_name='测评简介'),
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='is_online',
            field=models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('inprogress', '完善中')], max_length=30, verbose_name='测评上线状态'),
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='nums_eval',
            field=models.IntegerField(verbose_name='测评问题数量'),
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='price',
            field=models.CharField(max_length=20, verbose_name='测评价格'),
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='options',
            name='question',
            field=models.ManyToManyField(to='psytests.MentalEvaluation', verbose_name='对应问题'),
        ),
        migrations.DeleteModel(
            name='EvalQuestion',
        ),
        migrations.DeleteModel(
            name='UserEvaluation',
        ),
        migrations.DeleteModel(
            name='UserReviewForEvaluation',
        ),
    ]
