# Generated by Django 2.0 on 2020-03-29 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psytests', '0013_auto_20200329_0133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='options',
            options={'verbose_name': '选项', 'verbose_name_plural': '选项'},
        ),
        migrations.RenameField(
            model_name='mentalevaluation',
            old_name='created_on',
            new_name='eval_created_on',
        ),
        migrations.RenameField(
            model_name='mentalevaluation',
            old_name='dimension',
            new_name='eval_dimension',
        ),
        migrations.RenameField(
            model_name='mentalevaluation',
            old_name='intro',
            new_name='eval_intro',
        ),
        migrations.RenameField(
            model_name='mentalevaluation',
            old_name='is_online',
            new_name='eval_is_online',
        ),
        migrations.RenameField(
            model_name='mentalevaluation',
            old_name='price',
            new_name='eval_price',
        ),
        migrations.RenameField(
            model_name='mentalevaluation',
            old_name='nums_eval',
            new_name='eval_ques_nums',
        ),
        migrations.RenameField(
            model_name='mentalevaluation',
            old_name='title',
            new_name='eval_title',
        ),
        migrations.RenameField(
            model_name='options',
            old_name='o_desc',
            new_name='option_desc',
        ),
        migrations.RemoveField(
            model_name='options',
            name='o_id',
        ),
    ]
