# Generated by Django 2.0 on 2020-03-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psytests', '0014_auto_20200329_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='question',
        ),
        migrations.AddField(
            model_name='mentalevaluation',
            name='questions',
            field=models.ManyToManyField(to='psytests.Options', verbose_name='对应问题'),
        ),
    ]
