# Generated by Django 2.0 on 2020-04-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psytests', '0012_userevalquestioninfo'),
        ('psytests', '0015_auto_20200329_0224'),
    ]

    operations = [
    ]
