# Generated by Django 2.2 on 2020-02-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalevaluation',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
