# Generated by Django 2.2 on 2020-02-21 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20200221_0142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentalevaluation',
            options={'ordering': ['eval_id']},
        ),
    ]
