# Generated by Django 2.2 on 2020-03-02 00:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_auto_20200221_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalevaluation',
            name='eval_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '焦虑'), ('2', '抑郁')], max_length=3),
        ),
    ]
