# Generated by Django 2.2 on 2020-03-02 01:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_auto_20200302_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentalevaluation',
            name='eval_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '分类1'), ('2', '分类2'), ('3', '分类3')], max_length=5),
        ),
    ]
