# Generated by Django 2.2 on 2020-03-02 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_auto_20200302_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevaluation',
            name='user_count',
        ),
    ]
