# Generated by Django 2.2 on 2020-03-02 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_remove_userevaluation_user_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentalevaluation',
            name='discount_price',
            field=models.FloatField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userevaluation',
            name='user_count',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='price',
            field=models.FloatField(max_length=20),
        ),
    ]
