# Generated by Django 2.2 on 2020-03-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_auto_20200302_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevaluation',
            name='user_count',
        ),
    ]
