# Generated by Django 2.2 on 2020-03-02 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0009_remove_userevaluation_user_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEvaluation',
        ),
    ]
