# Generated by Django 2.2 on 2020-03-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0010_delete_userevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvaluation',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('eval_id', models.CharField(max_length=200)),
                ('eval_score', models.IntegerField()),
                ('user_count', models.IntegerField()),
                ('eval_result', models.CharField(max_length=100)),
                ('created_on', models.CharField(max_length=200)),
                ('payment_status', models.CharField(choices=[('paid', 'paid'), ('not paid', 'not paid')], max_length=20)),
                ('mentalEvaluation', models.ManyToManyField(to='django_app.MentalEvaluation')),
            ],
        ),
    ]
