# Generated by Django 2.2 on 2020-03-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0013_auto_20200302_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevaluation',
            name='mentalEvaluation',
        ),
        migrations.AlterField(
            model_name='userevaluation',
            name='payment_status',
            field=models.CharField(choices=[('1', 'paid'), ('0', 'not paid')], max_length=20),
        ),
    ]
