# Generated by Django 2.2 on 2020-03-22 03:15

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0014_auto_20200302_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvalQuestionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_id', models.CharField(max_length=200, verbose_name='测评id')),
                ('user_id', models.CharField(max_length=200, verbose_name='用户id')),
                ('q_id', models.IntegerField(verbose_name='')),
                ('user_selection', models.CharField(max_length=200, verbose_name='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='mentalevaluation',
            options={'ordering': ['eval_id'], 'verbose_name': '心理测评', 'verbose_name_plural': '心理测评'},
        ),
        migrations.AlterModelOptions(
            name='userevaluation',
            options={'verbose_name': '用户测评信息', 'verbose_name_plural': '用户测评信息'},
        ),
        migrations.AlterModelOptions(
            name='userreviewforevaluation',
            options={'verbose_name': '用户评价', 'verbose_name_plural': '用户评价'},
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='avatar',
            field=models.CharField(max_length=200, verbose_name='轮播图'),
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='created_on',
            field=models.CharField(max_length=200, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='discount_price',
            field=models.FloatField(max_length=20, verbose_name='折扣价格'),
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='eval_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='测评id'),
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='eval_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '成长'), ('2', '情感'), ('3', '人际关系')], max_length=5, verbose_name='测评类型'),
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='intro',
            field=models.TextField(verbose_name='一句话简介'),
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='is_online',
            field=models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('inprogress', '完善中')], max_length=30, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='nums_eval',
            field=models.IntegerField(verbose_name='测评次数'),
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='price',
            field=models.FloatField(max_length=20, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='ques_num',
            field=models.IntegerField(verbose_name='题目数量'),
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='state',
            field=models.IntegerField(verbose_name='测评状态'),
        ),
        migrations.AlterField(
            model_name='mentalevaluation',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='userevaluation',
            name='created_on',
            field=models.CharField(max_length=200, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userevaluation',
            name='eval_id',
            field=models.CharField(max_length=200, verbose_name='测评id'),
        ),
        migrations.AlterField(
            model_name='userevaluation',
            name='eval_result',
            field=models.CharField(max_length=100, verbose_name='测评结果'),
        ),
        migrations.AlterField(
            model_name='userevaluation',
            name='eval_score',
            field=models.IntegerField(verbose_name='测评分数'),
        ),
        migrations.AlterField(
            model_name='userevaluation',
            name='payment_status',
            field=models.CharField(choices=[('paid', ''), ('not paid', '')], max_length=20, verbose_name='付款状态'),
        ),
        migrations.AlterField(
            model_name='userevaluation',
            name='user_id',
            field=models.CharField(max_length=200, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='userreviewforevaluation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userreviewforevaluation',
            name='eval_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='测评id'),
        ),
        migrations.AlterField(
            model_name='userreviewforevaluation',
            name='review',
            field=models.TextField(verbose_name='评价'),
        ),
        migrations.AlterField(
            model_name='userreviewforevaluation',
            name='user_id',
            field=models.CharField(max_length=200, verbose_name='用户id'),
        ),
        migrations.CreateModel(
            name='EvalQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.IntegerField(auto_created=True, verbose_name='问题id')),
                ('q_desc', models.CharField(max_length=3000, verbose_name='问题描述')),
                ('reverse_scoring', models.BooleanField(choices=[(False, '正向'), (True, '反向')], default=False, verbose_name='反向计分')),
                ('dimension', models.IntegerField(choices=[(1, '一'), (2, '二'), (3, '三')], default=1, verbose_name='维度')),
                ('eval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.MentalEvaluation', verbose_name='对应测评')),
            ],
            options={
                'verbose_name': '测评问题',
                'verbose_name_plural': '测评问题',
                'ordering': ['q_id'],
            },
        ),
    ]
