# Generated by Django 2.2 on 2020-03-22 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0015_auto_20200322_0315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evalquestion',
            old_name='eval',
            new_name='eval_id',
        ),
    ]
