# Generated by Django 2.2 on 2020-03-22 22:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0016_auto_20200322_0400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userevalquestioninfo',
            options={'ordering': ['user_id'], 'verbose_name': '用户id', 'verbose_name_plural': '用户id'},
        ),
        migrations.RemoveField(
            model_name='userevalquestioninfo',
            name='user_selection',
        ),
        migrations.AlterField(
            model_name='userevalquestioninfo',
            name='eval_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.MentalEvaluation', verbose_name='测评id'),
        ),
        migrations.AlterField(
            model_name='userevalquestioninfo',
            name='q_id',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='django_app.EvalQuestion', verbose_name='问题id'),
        ),
        migrations.AlterField(
            model_name='userevalquestioninfo',
            name='user_id',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='django_app.UserEvaluation', verbose_name='用户id'),
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.IntegerField(auto_created=True, verbose_name='选项id')),
                ('o_desc', models.CharField(max_length=3000, verbose_name='选项描述')),
                ('question', models.ManyToManyField(to='django_app.EvalQuestion', verbose_name='对应问题')),
            ],
            options={
                'verbose_name': '选项',
                'ordering': ['o_id'],
                'verbose_name_plural': '选项',
            },
        ),
        migrations.AddField(
            model_name='userevalquestioninfo',
            name='o_id',
            field=models.ForeignKey(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='django_app.Options', verbose_name='选项id'),
            preserve_default=False,
        ),
    ]
