# Generated by Django 2.2 on 2020-03-22 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0017_auto_20200322_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevalquestioninfo',
            name='o_id',
        ),
        migrations.DeleteModel(
            name='Options',
        ),
    ]
