# Generated by Django 2.2 on 2020-03-22 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0018_auto_20200322_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.IntegerField(auto_created=True, verbose_name='选项id')),
                ('o_desc', models.CharField(max_length=3000, verbose_name='选项描述')),
                ('question', models.ManyToManyField(to='django_app.EvalQuestion', verbose_name='对应问题')),
            ],
            options={
                'verbose_name_plural': '选项',
                'ordering': ['o_id'],
                'verbose_name': '选项',
            },
        ),
        migrations.AddField(
            model_name='userevalquestioninfo',
            name='o_id',
            field=models.ForeignKey(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='django_app.Options', verbose_name='选项id'),
            preserve_default=False,
        ),
    ]
