# Generated by Django 2.2 on 2020-03-22 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0019_auto_20200322_2333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='EvalOptions',
        ),
    ]
