# Generated by Django 2.2 on 2020-03-22 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0020_auto_20200322_2334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvalOptions',
            new_name='Options',
        ),
    ]
