# Generated by Django 2.2 on 2020-03-22 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0021_auto_20200322_2335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEvalQuestionInfo',
        ),
    ]
