# Generated by Django 2.0 on 2020-04-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200326_1159'),
        ('users', '0010_userreport'),
    ]

    operations = [
    ]
