# Generated by Django 2.0 on 2020-03-06 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='轮播图')),
                ('url', models.URLField(verbose_name='访问地址')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=100, verbose_name='优惠券')),
                ('coupon_type', models.CharField(choices=[('默认', 'default'), ('节日', 'holiday'), ('其他', 'others')], default='default', max_length=20, verbose_name='优惠券类型')),
                ('use_condition', models.IntegerField(default=10, verbose_name='使用条件')),
                ('available_date', models.DateField(default=datetime.datetime.now, verbose_name='有效期')),
                ('get_type', models.CharField(choices=[('推送', 'push'), ('领取', 'pull')], default='push', max_length=20, verbose_name='获得方式')),
                ('get_condition', models.CharField(choices=[('新用户', 'new_user'), ('非会员', 'non_vip'), ('会员', 'vip')], default='non_vip', max_length=20, verbose_name='获得条件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('valid_date', models.DateField(verbose_name='可领取时间')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
            },
        ),
        migrations.CreateModel(
            name='VIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='价格')),
            ],
            options={
                'verbose_name': '会员',
                'verbose_name_plural': '会员',
            },
        ),
    ]
