# Generated by Django 2.0 on 2020-04-08 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='轮播图')),
                ('url', models.URLField(verbose_name='访问地址')),
                ('index', models.IntegerField(default=100, verbose_name='顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=100, verbose_name='优惠券')),
                ('coupon_type', models.CharField(choices=[('default', '默认'), ('holiday', '节日'), ('others', '其他')], default='default', max_length=20, verbose_name='优惠券类型')),
                ('coupon_valid_date', models.DateTimeField(default=datetime.datetime(2020, 5, 8, 13, 7, 26, 156714), verbose_name='有效期')),
                ('get_type', models.CharField(choices=[('push', '推送'), ('pull', '领取')], default='push', max_length=20, verbose_name='获得方式')),
                ('get_condition', models.CharField(choices=[('new_user', '新用户'), ('non_vip', '非会员'), ('vip', '会员')], default='vip', max_length=20, verbose_name='获得条件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('available_date', models.DateField(default=datetime.datetime(2020, 4, 9, 13, 7, 26, 156775), verbose_name='可领取时间')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
            },
        ),
        migrations.CreateModel(
            name='VIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_type', models.CharField(choices=[('normal', '普通会员'), ('advanced', '高级会员')], default='normal', max_length=100, verbose_name='会员类型')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('vip_valid_date', models.DateTimeField(default=datetime.datetime(2020, 5, 8, 13, 7, 26, 156357), verbose_name='有效期')),
            ],
            options={
                'verbose_name': '会员',
                'verbose_name_plural': '会员',
            },
        ),
    ]
