# Generated by Django 2.0 on 2020-03-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_auto_20200306_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='VIP_type',
            field=models.CharField(choices=[('normal', '普通会员'), ('advanced', '高级会员')], default='normal', max_length=100, verbose_name='会员类型'),
        ),
    ]
