# Generated by Django 2.0 on 2020-03-07 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_vip_vip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='valid_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 2, 0, 7, 574814), verbose_name='有效期'),
        ),
    ]
