# Generated by Django 2.0 on 2020-03-10 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_auto_20200307_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='valid_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 15, 3, 50, 278626), verbose_name='有效期'),
        ),
    ]
