# Generated by Django 2.0 on 2020-03-11 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0007_auto_20200311_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='valid_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 6, 36, 0, 752276), verbose_name='有效期'),
        ),
    ]
