# Generated by Django 2.0 on 2020-03-23 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0009_auto_20200311_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='valid_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 2, 16, 48, 622460), verbose_name='有效期'),
        ),
    ]
