# Generated by Django 2.0 on 2020-03-24 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0013_auto_20200323_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='valid_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 23, 14, 8, 39, 517870), verbose_name='有效期'),
        ),
    ]
