# Generated by Django 2.0 on 2020-03-29 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0013_auto_20200323_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='valid_date',
        ),
        migrations.RemoveField(
            model_name='vip',
            name='valid_date',
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_valid_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 0, 41, 7, 922812), verbose_name='有效期'),
        ),
        migrations.AddField(
            model_name='vip',
            name='vip_valid_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 0, 41, 7, 922186), verbose_name='有效期'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='available_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 30, 0, 41, 7, 922927), verbose_name='可领取时间'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='get_condition',
            field=models.CharField(choices=[('new_user', '新用户'), ('non_vip', '非会员'), ('vip', '会员')], default='vip', max_length=20, verbose_name='获得条件'),
        ),
    ]
