# Generated by Django 2.0 on 2020-03-29 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0015_auto_20200329_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vip',
            old_name='VIP_type',
            new_name='vip_type',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='available_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 30, 1, 38, 27, 281823), verbose_name='可领取时间'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_valid_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 1, 38, 27, 281757), verbose_name='有效期'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='vip_valid_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 1, 38, 27, 281393), verbose_name='有效期'),
        ),
    ]
