# Generated by Django 2.0 on 2020-03-26 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0015_auto_20200324_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='valid_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 11, 59, 19, 234982), verbose_name='有效期'),
        ),
    ]
