# Generated by Django 2.0 on 2020-03-29 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0017_auto_20200329_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='available_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 30, 1, 49, 52, 619659), verbose_name='可领取时间'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_valid_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 1, 49, 52, 619587), verbose_name='有效期'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='vip_valid_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 28, 1, 49, 52, 619204), verbose_name='有效期'),
        ),
    ]
