# Generated by Django 2.0 on 2020-04-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0016_auto_20200326_1159'),
        ('promotions', '0024_auto_20200407_0423'),
    ]

    operations = [
    ]
