# Generated by Django 2.0 on 2020-04-08 13:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('psytests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='popup/%Y/%m', verbose_name='弹窗')),
                ('url', models.URLField(verbose_name='访问地址')),
                ('status', models.IntegerField(choices=[(0, 'off'), (1, 'on')], default=0, verbose_name='状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '弹窗',
                'verbose_name_plural': '弹窗',
            },
        ),
        migrations.CreateModel(
            name='UserEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_score', models.IntegerField(verbose_name='测评得分')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, max_length=200, verbose_name='评价日期')),
                ('payment_status', models.CharField(choices=[('paid', '已付款'), ('not paid', '未付款')], default='paid', max_length=20)),
            ],
            options={
                'verbose_name': '用户测评信息',
                'verbose_name_plural': '用户测评信息',
            },
        ),
        migrations.CreateModel(
            name='UserPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='付款金额')),
                ('payment_type', models.CharField(choices=[('pay_test', '测评购买'), ('new_vip', '会员购买'), ('renew_vip', '会员续费')], max_length=30, verbose_name='付费类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='购买时间')),
            ],
            options={
                'verbose_name': '付款信息',
                'verbose_name_plural': '付款信息',
            },
        ),
        migrations.CreateModel(
            name='UserReviewForEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=3000, verbose_name='用户评价')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, verbose_name='评价日期')),
                ('review_eval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psytests.MentalEvaluation', verbose_name='测评')),
            ],
            options={
                'verbose_name': '用户评价',
                'verbose_name_plural': '用户评价',
            },
        ),
    ]
