# Generated by Django 2.0 on 2020-03-06 03:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0002_auto_20200306_0309'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyVIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='购买时间')),
                ('VIP_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.VIP', verbose_name='会员类型')),
                ('VIP_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='会员用户')),
            ],
            options={
                'verbose_name': '会员购买',
                'verbose_name_plural': '会员购买',
            },
        ),
        migrations.CreateModel(
            name='PopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(upload_to='popup/%Y/%m', verbose_name='弹窗')),
                ('url', models.URLField(verbose_name='访问地址')),
                ('status', models.IntegerField(choices=[(0, 'off'), (1, 'on')], default=0, verbose_name='顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='弹窗用户')),
            ],
            options={
                'verbose_name': '弹窗',
                'verbose_name_plural': '弹窗',
            },
        ),
    ]
