# Generated by Django 2.0 on 2020-03-07 02:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='付款金额')),
                ('payment_type', models.CharField(choices=[('pay_test', '测评购买'), ('new_vip', '会员购买'), ('renew_vip', '会员续费')], max_length=30, verbose_name='付费类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='购买时间')),
                ('payment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户付款')),
            ],
            options={
                'verbose_name': '会员购买',
                'verbose_name_plural': '会员购买',
            },
        ),
        migrations.RemoveField(
            model_name='buyvip',
            name='VIP_type',
        ),
        migrations.RemoveField(
            model_name='buyvip',
            name='VIP_user',
        ),
        migrations.AlterField(
            model_name='popup',
            name='status',
            field=models.IntegerField(choices=[(0, 'off'), (1, 'on')], default=0, verbose_name='状态'),
        ),
        migrations.DeleteModel(
            name='BuyVIP',
        ),
    ]
