# Generated by Django 2.0 on 2020-03-10 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20200307_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', verbose_name='弹窗用户'),
        ),
        migrations.AlterField(
            model_name='userpay',
            name='payment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', verbose_name='用户付款'),
        ),
    ]
