# Generated by Django 2.0 on 2020-03-29 01:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psytests', '0013_auto_20200329_0133'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0004_auto_20200310_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_score', models.IntegerField(verbose_name='测评得分')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, max_length=200, verbose_name='评价日期')),
                ('payment_status', models.CharField(choices=[('paid', '已付款'), ('not paid', '未付款')], default='paid', max_length=20)),
                ('eval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psytests.MentalEvaluation', verbose_name='测评ID')),
                ('eval_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '用户测评信息',
                'verbose_name_plural': '用户测评信息',
            },
        ),
        migrations.CreateModel(
            name='UserReviewForEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=3000, verbose_name='用户评价')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, verbose_name='评价日期')),
                ('review_eval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psytests.MentalEvaluation', verbose_name='测评')),
                ('review_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评价用户')),
            ],
            options={
                'verbose_name': '用户评价',
                'verbose_name_plural': '用户评价',
            },
        ),
    ]
