# Generated by Django 2.0 on 2020-03-29 02:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0005_userevaluation_userreviewforevaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popup',
            name='target_user',
        ),
        migrations.AddField(
            model_name='popup',
            name='target_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='弹窗用户'),
        ),
    ]
